version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        #Exclude ports to force access through nginx
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"